### ISSUE TITLE
[SIGSEGV] valgrind reports Invalid Read 

### ISSUE THREAD

**Issue by sunneo** [yppan/Huffman-PNG-Compress#1]
https://github.com/yppan/Huffman-PNG-Compress/blob/adeeda5c794b348d2ce89802703fdafb8df25afb/huffman.c#L69
```
for (c = 0; c < GRAY_SCALE; ++c){
        if (frequency[i] > 0){
            num_active++;
        }
}
```
this one iterates c from 0...GRAY_SCALE
while accessing to array did not utilize the iterator c, it uses a variable i instead, 
in which variable i is not guaranteed to located within array range of frequency.

**Comment by TheCloudlet** [comment]
Thanks! Such a stupid mistake!
